---
title: "Example Plots"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(dplyr)
library(p8105.datasets)
library(plotly)

data(instacart)

instacart_df = instacart %>%
  filter(aisle %in% c("fresh vegetables", "fresh fruits", "packaged vegetables fruits",  "yogurt", "packaged cheese", "water seltzer sparkling water", "milk", "chips pretzels",  "soy lactosefree"))

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r charta}

instacart_df %>% 
  group_by(aisle) %>%
  summarize(n = n()) %>%
  mutate(
    aisle = as.factor(aisle),
    aisle = fct_reorder(aisle, n)
  ) %>%
  plot_ly(x = ~aisle, y = ~n, color = ~aisle, type = "bar", colors = "viridis") %>%
    layout(
    title = 'Total Number of Orders for the 10 Most Popular Aisles', 
    xaxis = list(title = 'Aisle'),
    yaxis = list(title = 'Number of Orders'))


```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r chartb}


data(instacart)

instacart_df = instacart %>%
  filter(aisle %in% c("fresh vegetables", "fresh fruits", "packaged vegetables fruits",  "yogurt", "packaged cheese", "water seltzer sparkling water", "milk", "chips pretzels",  "soy lactosefree"))

instacart_df %>%
  filter(product_name %in% c("Baby Brie", "Cheddar Cheese", "Arugula")) %>%
  plot_ly(y = ~order_hour_of_day, 
          color = ~product_name, 
          type = "box", 
          colors = "viridis") %>% 
  layout(
    title = 'Distribution of Order Times by Aisle', 
    xaxis = list(title = 'Order Day of Week'),
    yaxis = list(title = 'Order Hour of Day', range = c(0,24)))


```

### Chart C

```{r chartc}

instacart_df %>% tail()

instacart_df %>%
  filter(product_name %in% c("Baby Brie", "Cheese, Asiago")) %>%
  plot_ly(
  x = ~days_since_prior_order, y = ~order_hour_of_day, type = "scatter", mode = "markers",
  color = ~product_name) %>%
    layout(
    title = 'Scatterplot of Days Since Prior Order vs Order Hour of Day', 
    xaxis = list(title = 'Days Since Prior Order'),
    yaxis = list(title = 'Order Hour of Day', range = c(0,24)))

```


